
---

# ===@@@!!!patroni vars!!!@@@===
ansible_user            : centos
ansible_ssh_private_key : /Users/akatruk/.ssh/id_rsa.pub

cname1: srv1
ip_address1: 172.31.42.18
cname2: srv2
ip_address2: 172.31.44.249
cname3: srv3
ip_address3: 172.31.39.214
cname3: srv4
ip_address4: 172.31.32.37
cname3: srv5
ip_address5: 172.31.34.213
virtual_ip: 172.31.21.200
network_pg: '0.0.0.0/0'
cluster_name: demo_cluster

hosts: 172.31.42.18:2379, 172.31.44.249:2379, 172.31.39.214:2379, 172.31.32.37:2379, 172.31.34.213:2379
# patroni_scope: patroniscope

# ===@@@!!!access to database as postgres user !!!@@@===
password_postgres: 'super2EassworD11'

# Posgres parameters
patroni_pg_max_connections: 700
shared_buffers: 128MB
work_mem: 10485kB
effective_cash_size: 3GB

# ====== vars VM deploy ======
vapp_name_vcd: k8s-prod_db
source_catalog_name: LSP OS Catalog
network: K8s-ProdDB-Int
storage_profile: LifeStyle-Platform-FAS-Medium
source_template_name: TEMPLATE
target_vdc: LifeStyle-Platform
virtual_cpus: 2
memory: 4096
Additional_Disk_Size: 51200
vm_name:
       - M1K8SPLDB10
       - M1K8SPLDB11
       - M1K8SPLDB12
ip_address: 
       - 10.10.11.11
       - 10.10.11.12
       - 10.10.11.13

       